default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ico-app-ac-cesar

test:
  <<: *default
  database: ico-app-ac-cesar_test

production:
  <<: *default
  database: ico-app-ac-cesar
  username: ico-app-ac-cesar
  password: <%= ENV['ICO-APP-AC-CESAR_DATABASE_PASSWORD'] %>
